# Generated by Django 2.1.7 on 2019-05-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=50, verbose_name='用户id')),
                ('types', models.IntegerField(choices=[(1, '举报'), (0, '反馈')], default=0, verbose_name='类型')),
                ('art', models.IntegerField(default=0, verbose_name='列表id')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('content', models.CharField(max_length=120, verbose_name='内容')),
                ('adate', models.DateField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '反馈建议',
                'verbose_name_plural': '反馈建议',
                'db_table': 'wp_advice',
            },
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=50, verbose_name='用户id')),
                ('types', models.CharField(default='游戏', max_length=8, verbose_name='类型')),
                ('img', models.ImageField(max_length=120, upload_to='images/art/%Y/%m', verbose_name='图像')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('addr', models.CharField(max_length=30, verbose_name='地址')),
                ('detail', models.CharField(max_length=200, verbose_name='详情')),
                ('sdate', models.DateTimeField(verbose_name='开始时间')),
                ('edate', models.DateTimeField(verbose_name='结束时间')),
                ('adate', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '列表',
                'verbose_name_plural': '列表',
                'db_table': 'wp_art',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('img', models.ImageField(max_length=120, upload_to='images/banner/%Y/%m', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=1, verbose_name='顺序')),
                ('adate', models.DateField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'wp_banner',
            },
        ),
    ]
