# Generated by Django 2.1.7 on 2019-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='types',
            field=models.IntegerField(choices=[(1, '游戏'), (2, '旅游'), (3, '唱歌'), (4, '其它')], default=1, verbose_name='类型'),
        ),
    ]
