# Generated by Django 2.1.7 on 2019-05-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20190510_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='isdel',
            field=models.IntegerField(blank=True, choices=[(1, '删除'), (0, '正常')], default=0, null=True, verbose_name='是否删除'),
        ),
    ]
