# Generated by Django 2.1.7 on 2019-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_art_isdel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='img',
            field=models.ImageField(max_length=222, upload_to='images/art/%Y/%m', verbose_name='图像'),
        ),
    ]
